### ISSUE TITLE
Upgrade gcc build script to build a newer gcc

### ISSUE THREAD

**Issue by iankronquist** [iankronquist/kernel-of-truth#41]
Pretty simple actually.

**Comment by iankronquist** [comment]
Partially fixed by @Herbstein's latest PR #46

**Comment by Herbstein** [comment]
Do you mean implementing this in something like Python, or just reworking the existing script?

**Comment by iankronquist** [comment]
I meant updating the existing script to build a newer gcc.

**Comment by Herbstein** [comment]
I can take a look at that. I was looking to do something menial anyway.

**Comment by Herbstein** [comment]
I updated all used components to their latest versions and it builds nicely, as far as I can see. The updated version of `gcc` does create some errors, however. I'm not familiar enough with the paging code to fix them.

**Comment by Herbstein** [comment]
All the errors are bceause of the `CUR_PAGE_DIRECTORY_ADDR` macro in paging.h. `~0` is used, which turns it into the max negative number. GCC throws an error when left-shifting a negative number.

**Comment by iankronquist** [comment]
Alright, I'll take a look.

**Comment by iankronquist** [comment]
Ah, I see. You can replaced that little macro with this:
```c
#define CUR_PAGE_DIRECTORY_ADDR ((uint32_t*)(0xfffff000))
```

**Comment by Herbstein** [comment]
That did the trick. I'll create the pull request.
