### ISSUE TITLE
Clean up tlibc

### ISSUE THREAD

**Issue by iankronquist** [iankronquist/kernel-of-truth#58]
* We don't need the crappy printf
* We do need the string functions (memset etc.) They could be moved to libk.

**Comment by iankronquist** [comment]
This does include removing the tests for kassert which are both out of date and difficult to test properly.

**Comment by Herbstein** [comment]
Is that what you have in mind? I simply moved the `string.h` functions into seperate files in libk. tlibc isn't being build at the moment because a conflict in the function names would happen otherwise.

**Comment by iankronquist** [comment]
@Herbstein that seems reasonable. I can't test it until around the 11th of July as I'm on vacation in Eastern Europe.

**Comment by Herbstein** [comment]
Enjoy your vacation then!

**Comment by iankronquist** [comment]
@Herbstein I have returned to civilization, so if you're still interested in submitting a proposal, please open one!

**Comment by Herbstein** [comment]
Will do.

**Comment by Herbstein** [comment]
It is in #59.
